### ISSUE TITLE
Could you provide the downloading link of the generated dataset?

### ISSUE THREAD

**Issue by Z7zuqer** [ZhangxinruBIT/CarveMix#1]
Thanks for your wonderful project!

Could you provide the generated dataset which is used in your experiments? Or if i follow the instructions and generate the total training items to an amount of 1000, i will reproduce your results. I'm wondering whether variance exists in the process of generating.

Really appreciate that you could reply!

Best,
Hao.

**Comment by ZhangxinruBIT** [comment]
Sure, I will sort out nnUNet_raw_data  and nnUNet_trained_models generated during training in ATLAS dataset 100% experiment task later as well as specific data partitioning of ATLAS dataset and data spilit modifications in nnUNet.

**Comment by ZhangxinruBIT** [comment]
I have provided the link in the main branch, because the file is too large and does not support github upload, so it is stored in the web disk, I hope it can help you.

**Comment by gitouni** [comment]
Close this issue because there haven't been any new issues or replies for long.
