### ISSUE TITLE
Distribution of Lambda

### ISSUE THREAD

**Issue by rickymwalsh** [ZhangxinruBIT/CarveMix#4]
Hi there,

Thanks a lot for the nice paper and for making your code available online!

I was comparing the implementation of lambda to the description in the paper and I thought I saw a discrepancy so wanted to check with you in case I misunderstood the implementation.

In the paper,   
$`\lambda \sim \frac{1}{2}U(-\frac{1}{2} |D(Y_{i})_{min}|, 0) \quad  + \quad  \frac{1}{2}U(0, |D(Y_i)_{min}|)`$

But it seems to me that the implementation in the code leads to 
$`\lambda \sim \delta \ U(-\frac{1}{2} |D(Y_{i})_{min}|, 0) \quad  + \quad  (1-\delta) \ U(0, |D(Y_i)_{min}|)`$
where   $`\delta \sim bernouilli(\frac{1}{2})`$

With the first distribution, it would mean the minimum possible value would be $\frac{1}{4}$ times the min distance, and adding the two uniform distributions would mean that lambda is more likely to be closer to zero than at the lower or upper bound, i.e. the PDF would no longer be flat.

Let me know if you think I made a mistake in understanding your implementation.

Thanks,
Ricky

**Comment by ZhangxinruBIT** [comment]
Hi, Ricky. 

Please note that $\lambda$ is a signed value. The term $\frac{1}{2}$ does not mean multiplying by 1/2. Rather, it indicates a 50% probability of selecting the left part of the equation $`\lambda \sim \left(-\frac{1}{2} |D(Y_{i})_{min}|, 0\right)`$. In this case, the value of $\lambda$ will result in a mask smaller than the annotation (potentially minimum around $\frac{1}{2}$ of the distance $`|D(Y_{i})_{min}|`$). Conversely, there is also a 50% probability of selecting the right part of the equation $`\lambda \sim U\left(0, |D(Y_i)_{min}|\right)`$, where the value of $\lambda$ will produce a mask larger than the annotation (possibly maximum around $2$ times the distance $`|D(Y_{i})_{min}|`$).

**Comment by rickymwalsh** [comment]
Hi Xinru, 

Thanks for the clarification, that is clear to me now. That aligns with the second formulation I wrote above with the $\delta\$ term or I guess another way would be 
$`\begin{cases} U(-\frac{1}{2} |D(Y_{i})_{min}|, 0), \quad p=0.5 \\ U(0, |D(Y_{i})_{min}|), \quad p=0.5 \\ \end{cases} `$

Thanks for the quick response, I'll close the issue now.
